name: XMod
version: 2.63
date: 26/09/2017
description: |
    Crossed Modules and Cat1-Groups

authors:
    - name: Christopher D. Wensley
      url: http://pages.bangor.ac.uk/~mas023/
    - name: Murat Alp
      url: mailto:muratalp@nigde.edu.tr
    - name: Alper Odabas
      url: mailto:aodabas@ogu.edu.tr
    - name: Enver Onder Uslu
      url: mailto:enveruslu@ogu.edu.tr

maintainers:
    - name: Christopher D. Wensley
      url: http://pages.bangor.ac.uk/~mas023/

GAP: ">=4.8.7"

needed-pkgs:
    - name: "Utils"
      version: ">= 0.48"
      url: "https://gap-packages.github.io/utils"
    - name: "groupoids"
      version: ">= 1.52"
      url: "https://gap-packages.github.io/groupoids/"
    - name: "Hap"
      version: ">= 1.11.13"
      url: "http://hamilton.nuigalway.ie/Hap/www"
    - name: "AutPGrp"
      version: ">= 1.6"
      url: "http://www.icm.tu-bs.de/~beick/so.html"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/xmod/
readme: README.md
packageinfo: https://gap-packages.github.io/xmod/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/xmod/releases/download/v2.63/XMod-2.63.tar.gz

abstract: |
    The <span class="pkgname">XMod</span> package provides a collection   of functions for computing with crossed modules and cat1-groups, their derivations and sections, morphisms of these structures, and higher-dimensional generalisations.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
